project: 
  type: website
  render:
    - "*.{qmd,R,py}"
    - "!utils.py"
  preview: 
    browser: true
  
website: 
  title: "Deepak Kumar"
  navbar: 
    left: 
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
        
format:
  html:
    theme: lux
    css: styles.css
    fontcolor: black
    linkcolor: white
    backgroundcolor: "#a1bbcc"
    monobackgroundcolor: red
    mainfont: "quarto-light"