project: 
  type: website
  
website: 
  title: "Deepak Kumar"
  navbar: 
    left: 
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
        
format:
  html:
    theme: lux
    fontcolor: black
    linkcolor: white
    backgroundcolor: "#a1bbcc"
    monobackgroundcolor: red
    mainfont: "quarto-light"