---
title: "About"
format: html
---

My name is Deepak Kumar. I am belongs to Agra, Uttar Pradesh. a city celebrated worldwide for its architectural marvels, rich cultural heritage, and timeless values. The city's legacy of craftsmanship, cultural fusion, and enduring traditions has profoundly influenced my worldview, instilling in me a deep appreciation for unity, social ethics, and intellectual curiosity. These values form the foundation of my academic and professional journey. I am trainee psychologist. If i talk about my educational background. I have completed Bachelor in specialized areas psychology, English Literature in 2021 from St.john's college and i have also completed Master's in Psychology from University of Allahabad in the year 2023 with first division achievements.

If i talk about my work experienced, i had being student counsellor during bachelor degree at St.john's College. and i worked as a vocational training at Sneh School for special children & Ahna Welfare with help of Neurodevelomental techniques as well as did work in clinical case studies through online internship during Covid period at Gautam Hospital in Jaipur. I have also worked as a Research Assistant at the Department of Psychology, University of Allahabad.

Recently, I also completed a one week residential bootcamp on Data Science at Sara Institute in Sonipat, Haryana. Besides, work fields, i also liked to travel and explore to know about Indian Cultures, I have visited more than 20+ states of India.

I proficient in SPSS, Rstudio, Quarto, Survey Design, Interview modulation and Psychopy.
I am passionate about helping individual achieve their personal and academic potentials.
I believed that, my interpersonal skills research experience and counselling expertise make me a strong cordinate for the role of psychologist.


