---
title: "About"
format: html
---

### Hello there!
I am Deepak kumar. I am enthusiasm to explore in research psychology background. I belongs to Agra, Uttar Pradesh. I have worked as research assistant in University of Allahabad and St.johns college which is affilation by Dr. B. R. Ambedkar University, Agra.

My academic path has been shaped by a strong interdisciplinary background and meaningful research experiences. During my time at the University of Allahabad, I had the privilege of engaging deeply with research, which refined my critical thinking and analytical skills. Immersing myself in studies spanning psychology, and ancient history allowed me to develop a nuanced understanding of human behavior, societal structures, and the intersections of tradition and modernity. These experiences not only broadened my intellectual horizons but also laid the groundwork for my commitment to impactful research.
 
I am also content creator in social media platform to make several content for Unique generative contents which is required to improve skills in softwares such as Adobe Premium Pro, Capcut, and Final cut pro. it enhance my skills in Content creation fields. 
